services:

  # Nginx Service
  nginx:
    image: nginx:alpine
    container_name: ${APP_SLUG}_nginx
    restart: unless-stopped
    ports:
      - "8888:80"
      - "8889:4200"
    volumes:
      - ./:/var/www
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app_network
    env_file:
      - .env.local
    depends_on:
      - php

  # Mariadb Service
  database:
    image: mariadb:latest
    container_name: ${APP_SLUG}_database
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      SERVICE_TAGS: ${APP_ENV}
      SERVICE_NAME: ${APP_SLUG}_database
      MYSQL_DATABASE: ${MARIADB_DATABASE}
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
    volumes:
      - /var/www/database:/var/lib/mysql/
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
      - ./docker/mysql/create-testing-database.sh:/docker-entrypoint-initdb.d/10-create-testing-database.sh
    networks:
      - app_network
    env_file:
      - .env.local

  # PHP Service
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: ${APP_SLUG}_php
    restart: unless-stopped
    environment:
      SERVICE_NAME: ${APP_SLUG}_php
      SERVICE_TAGS: ${APP_ENV}
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - app_network
    env_file:
      - .env.local
    depends_on:
      - database

  ###> symfony/mailer ###
  mailer:
    image: mailhog/mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - app_network
    container_name: ${APP_SLUG}_mailer

# Docker Networks
networks:
  app_network:
    driver: bridge
